name: 'WordPress Plugin Release Action'
author: 'Sultan Nasir Uddin'
description: 'Release WordPress plugin to wordpress.org SVN repository'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  slug:
    description: 'SVN slug'
    required: true
    default: ${{ github.event.repository.name }}
  username:
    description: 'SVN username'
    required: true
    default: ''
  password:
    description: 'SVN password'
    required: true
    default: ''
  version:
    description: 'Version'
    required: false
    default: ''
  generate_zip:
    description: 'Generate package zip file?'
    required: false
    default: ''
  dry_run:
    description: 'Dry run'
    required: false
    default: 'false'
  slack_webhook:
    description: 'Slack webhook URL'
    required: false
    default: ''
  slack_message:
    description: 'Slack message'
    required: false
    default: 'Deployed to wordpress.org successfully'

outputs:
  zip_path:
    description: 'Path to zip file'
    value: ${{ steps.deploy.outputs.zip_path }}
  version:
    description: 'Release version'
    value: ${{ steps.deploy.outputs.version }}

runs:
  using: 'composite'
  steps:
    - id: deploy
      shell: bash
      run: ./.github/actions/wordpress-plugin-release/run.sh
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        SLUG: ${{ inputs.slug }}
        VERSION: ${{ inputs.version }}
        GENERATE_ZIP: ${{ inputs.generate_zip }}
        DRY_RUN: ${{ inputs.dry_run }}
      # Post message to Slack channel
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      if: ${{ success() && inputs.slack_webhook != '' }}
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: ':rocket:'
        SLACK_TITLE: ":rocket: ${{ inputs.slug }} v${{ inputs.version }} has been released"
        SLACK_USERNAME: 'GitHub Actions'
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_FOOTER: ${{ inputs.slug }}-v${{ steps.deploy.outputs.version }}
        SLACK_MESSAGE: ${{ inputs.slack_message }}
        MSG_MINIMAL: true
