<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'WooCommerceVariationImages\\ByteKit\\' => array($vendorDir . '/byteever/bytekit-settings/src', $vendorDir . '/byteever/bytekit-plugin/src'),
);
