<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitc611663486000a2c78cce57f6534a6ee
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WooCommerceVariationImages\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WooCommerceVariationImages\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitc611663486000a2c78cce57f6534a6ee', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WooCommerceVariationImages\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitc611663486000a2c78cce57f6534a6ee', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WooCommerceVariationImages\Composer\Autoload\ComposerStaticInitc611663486000a2c78cce57f6534a6ee::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
