<?php

// autoload_static.php @generated by Composer

namespace WooCommerceVariationImages\Composer\Autoload;

class ComposerStaticInitc611663486000a2c78cce57f6534a6ee
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WooCommerceVariationImages\\ByteKit\\' => 35,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WooCommerceVariationImages\\ByteKit\\' => 
        array (
            0 => __DIR__ . '/..' . '/byteever/bytekit-settings/src',
            1 => __DIR__ . '/..' . '/byteever/bytekit-plugin/src',
        ),
    );

    public static $classMap = array (
        'WooCommerceVariationImages\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WooCommerceVariationImages\\ByteKit\\Admin\\Flash' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Flash.php',
        'WooCommerceVariationImages\\ByteKit\\Admin\\Notices' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Notices.php',
        'WooCommerceVariationImages\\ByteKit\\Admin\\Settings' => __DIR__ . '/..' . '/byteever/bytekit-settings/src/Admin/Settings.php',
        'WooCommerceVariationImages\\ByteKit\\Interfaces\\Pluginable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
        'WooCommerceVariationImages\\ByteKit\\Interfaces\\Scriptable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
        'WooCommerceVariationImages\\ByteKit\\Plugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Plugin.php',
        'WooCommerceVariationImages\\ByteKit\\Scripts' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Scripts.php',
        'WooCommerceVariationImages\\ByteKit\\Services' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Services.php',
        'WooCommerceVariationImages\\ByteKit\\Traits\\HasPlugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc611663486000a2c78cce57f6534a6ee::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc611663486000a2c78cce57f6534a6ee::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc611663486000a2c78cce57f6534a6ee::$classMap;

        }, null, ClassLoader::class);
    }
}
