<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'WooCommerceVariationImages\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WooCommerceVariationImages\\ByteKit\\Admin\\Flash' => $vendorDir . '/byteever/bytekit-plugin/src/Admin/Flash.php',
    'WooCommerceVariationImages\\ByteKit\\Admin\\Notices' => $vendorDir . '/byteever/bytekit-plugin/src/Admin/Notices.php',
    'WooCommerceVariationImages\\ByteKit\\Admin\\Settings' => $vendorDir . '/byteever/bytekit-settings/src/Admin/Settings.php',
    'WooCommerceVariationImages\\ByteKit\\Interfaces\\Pluginable' => $vendorDir . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
    'WooCommerceVariationImages\\ByteKit\\Interfaces\\Scriptable' => $vendorDir . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
    'WooCommerceVariationImages\\ByteKit\\Plugin' => $vendorDir . '/byteever/bytekit-plugin/src/Plugin.php',
    'WooCommerceVariationImages\\ByteKit\\Scripts' => $vendorDir . '/byteever/bytekit-plugin/src/Scripts.php',
    'WooCommerceVariationImages\\ByteKit\\Services' => $vendorDir . '/byteever/bytekit-plugin/src/Services.php',
    'WooCommerceVariationImages\\ByteKit\\Traits\\HasPlugin' => $vendorDir . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
);
