name: "Build and Release plugin"
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer
          
      - name: Setup github token
        run: composer config -g github-oauth.github.com ${{ secrets.ACCESS_TOKEN }}

      - name: Build
        run: |
          # composer install
          # composer update --no-dev --no-scripts
          npm install && npm run build
        
      - name: Release
        id: release
        uses: ./.github/actions/wordpress-plugin-release
        with:
          username: 'test'
          password: 'test'
          version: 1.0.4
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          generate_zip: 'true'
          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ steps.release.outputs.zip_path }}
